spring:
  application:
    name: Identification
  datasource:
    url: jdbc:postgresql://localhost:5432/identification
    username: identification
    password: abc123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect